default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  host: <%= ENV['MYSQL_SERVICE_HOST'] %>
  port: <%= ENV['MYSQL_SERVICE_PORT'] %>

development:
  <<: *default
  database: tantal_development

test:
  <<: *default
  database: tantal_test
