kind: Pod
apiVersion: v1beta1

id: mysql

nodeSelector:
  mysql: true

labels:
  name: mysql

desiredState:
  manifest:
    id: mysql
    version: v1beta1
    containers:
      - name: mysql
        image: dock:5000/mysql:5.6.21
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: q1w2e3r4
